#!/usr/bin/env python3
"""Regenerate pdfmd_unicode/_scripts.py, the Unicode Script property as ranges.

    python3 scripts/gen_unicode_scripts.py           # rewrite the table
    python3 scripts/gen_unicode_scripts.py --check   # fail if it has drifted

Python's own `unicodedata` has no Script property, which pdfmd needs to tell
an Arabic letter from a Han character. fontTools (a development-time tool, not
a dependency of pdfmd) carries the Unicode Character Database's Scripts.txt;
this folds it into one sorted list of (first, last, ISO 15924 code) ranges that
the package looks up by bisection. Unassigned code points (Zzzz) are left out.
The generated file is never edited by hand.
"""

from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "pdfmd_unicode" / "_scripts.py"


def build() -> tuple[str, list[tuple[int, int, str]]]:
    try:
        from fontTools import unicodedata as ftu
    except ImportError:
        sys.exit("fontTools is needed to regenerate the table (pip install fonttools)")
    ranges: list[tuple[int, int, str]] = []
    start = last = None
    current = None
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            code = "Zzzz"
        else:
            code = ftu.script(chr(cp))
        if code == "Zzzz":
            code = None
        if code != current or (last is not None and cp != last + 1):
            if current is not None:
                ranges.append((start, last, current))
            start, current = cp, code
        last = cp
    if current is not None:
        ranges.append((start, last, current))
    return unicodedata.unidata_version, ranges


def render(version: str, ranges: list[tuple[int, int, str]]) -> str:
    codes = sorted({code for _, _, code in ranges})
    index = {code: number for number, code in enumerate(codes)}
    lines = ['"""The Unicode Script property as ranges. GENERATED by scripts/gen_unicode_scripts.py."""',
             "", f'UNICODE_VERSION = "{version}"', "",
             "# ISO 15924 codes, indexed by the third column of RANGES.",
             "CODES = (" + ", ".join(repr(code) for code in codes) + ",)", "",
             "# (first code point, last code point, index into CODES), sorted.", "RANGES = ("]
    for first, last, code in ranges:
        lines.append(f"    ({first}, {last}, {index[code]}),")
    lines += [")", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated file differs")
    args = parser.parse_args()
    text = render(*build())
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != text:
            print(f"{TARGET} has drifted; run scripts/gen_unicode_scripts.py")
            return 1
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET} ({len(text) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
