#!/usr/bin/env python3
"""Regenerate pdfmd_unicode/_tessdata_catalog.py, the Tesseract language files `pdfmd --install ocr:LANG` can fetch.

    python3 scripts/gen_tessdata_catalog.py            # rewrite the catalog (needs network and `gh`)
    python3 scripts/gen_tessdata_catalog.py --check    # say whether it would change, write nothing

The files are the `tessdata_fast` models (Apache-2.0) of the tesseract-ocr project, taken at one
pinned commit, each with the git blob SHA-1 GitHub lists for it; pdfmd refuses a download that
does not match.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "pdfmd_unicode" / "_tessdata_catalog.py"
REPOSITORY = "tesseract-ocr/tessdata_fast"
TAG = "4.1.0"


def gh_json(path: str):
    return json.loads(subprocess.run(["gh", "api", path], capture_output=True, text=True, check=True).stdout)


def build() -> tuple[str, dict]:
    commit = gh_json(f"repos/{REPOSITORY}/commits/{TAG}")["sha"]
    tree = gh_json(f"repos/{REPOSITORY}/git/trees/{commit}")
    if tree.get("truncated"):
        raise SystemExit("the tree is truncated")
    languages = {}
    for entry in tree["tree"]:
        path = entry["path"]
        if entry["type"] == "blob" and path.endswith(".traineddata") and "/" not in path:
            languages[path[: -len(".traineddata")]] = {"sha1": entry["sha"], "size": entry["size"]}
    return commit, languages


def render(commit: str, languages: dict) -> str:
    lines = ['"""The Tesseract language files `pdfmd --install ocr:LANG` can fetch. GENERATED by scripts/gen_tessdata_catalog.py."""',
             "", f"REPOSITORY = {REPOSITORY!r}", f"COMMIT = {commit!r}", "", "# code: git blob SHA-1 and size of <code>.traineddata",
             "LANGUAGES = {"]
    for code in sorted(languages):
        lines.append(f"    {code!r}: ({languages[code]['sha1']!r}, {languages[code]['size']}),")
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render(*build())
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        print("up to date" if current == text else "would change")
        return 0 if current == text else 1
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
